/** Declaration file generated by dts-gen */

export = canadapost_api_alt;

declare class canadapost_api_alt {
    constructor(...args: any[]);

    createContractShipment(...args: any[]): void;

    createNonContractShipment(...args: any[]): void;

    discoverServices(...args: any[]): void;

    getRates(...args: any[]): void;

    getShipment(...args: any[]): void;

    getShipmentDetails(...args: any[]): void;

    getShipments(...args: any[]): void;

    getTrackingDetail(...args: any[]): void;

    getTrackingSummary(...args: any[]): void;

    refundNonContractShipment(...args: any[]): void;

    static CanadaPostError(...args: any[]): void;

    static ENDPOINT: string;

    static ENDPOINT_DEV: string;

    static checkResultFormat(...args: any[]): void;

    static formatDate(...args: any[]): void;

    static normalizeObject(...args: any[]): void;

    static setNamespace(...args: any[]): void;

}

declare namespace canadapost_api_alt {
    namespace CanadaPostError {
        const stackTraceLimit: number;

        function captureStackTrace(p0: any, p1: any): any;

    }

}


